language: go
sudo: false
go:
  - 1.x
  - tip
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
install:
  - make deps
  - make testdeps
  - make lintdeps
script:
  - make lint
  - make test
after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
